services:

  # 🛢️ SQL SERVER
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: task_sql
    environment:
      SA_PASSWORD: "YourStrong@Pass123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  # .NET API
  taskmanagement.api:
    build:
      context: .   
      dockerfile: src/TaskManagement.API/Dockerfile
    image: abadevops21/taskmanagement-api:latest
    container_name: task_api
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=TaskDb;User=sa;Password=YourStrong@Pass123;TrustServerCertificate=True;
    ports:
      - "5000:80"

  # ANGULAR CLIENT
  client:
    build:
      context: ./client-app/task-management-ui
      dockerfile: Dockerfile
    image: abadevops21/taskmanagement-client:latest
    container_name: task_client
    depends_on:
      - taskmanagement.api
    ports:
      - "4200:80"

volumes:
  sql_data: